#!/bin/bash
# this is an simple config for herbstluftwm

function hc() {
    herbstclient "$@"
}

# defining Mod1 config wide
Mod=Mod1

xsetroot -solid '#000000'

# dmenu
hc keybind $Mod-p spawn dmenu_run -b -nb '#000000' -nf '#888888' -sb '#ff6622' -sf '#222222'

# keybindings
hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close
hc keybind $Mod-Return spawn urxvtc

# tags
hc rename default 1 || true
for i in {1..9} ; do
    hc add "$i"
    hc keybind "$Mod-$i" use "$i"
    hc keybind "$Mod-Shift-$i" move "$i"
done

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-v split v 0.5
hc keybind $Mod-h split h 0.5

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# focus
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# colors
hc set frame_border_active_color '#49351D'
hc set frame_border_normal_color '#111111'
hc set frame_bg_normal_color '#BD9768'
hc set frame_bg_active_color '#BD8541'
hc set frame_border_width 1
hc set window_border_width 1
hc set window_gap 0
hc set window_border_normal_color '#111111'
hc set window_border_active_color '#FF6622'

hc keybind $Mod-space cycle_layout 1
