source "${HOME}/.zsh/aliases"
source "${HOME}/.zsh/colorz"
source "${HOME}/.zsh/completion"
source "${HOME}/.zsh/environment"
source "${HOME}/.zsh/functions"
source "${HOME}/.zsh/general_settings"
source "${HOME}/.zsh/history"
source "${HOME}/.zsh/keybindings"
source "${HOME}/.zsh/locales"
source "${HOME}/.zsh/prompt"

source "${HOME}/.zsh/git"
source "${HOME}/.zsh/ssh_conn_tmux"
source "${HOME}/.zsh/urgency_hint"
