" Don’t ensure compatibility with vi at all cost
set nocompatible

" Security
set modeline

" Should be given by the machine vim is installed on
runtime! debian.vim

" Set the titel for the terminal
set title

" Enable syntax
syntax on

" Enable line numbers
set nu

" Set background to dark
set bg=dark

" Defines the colorscheme that should be used
colorscheme elflord

" Better highlight of the line number that has focus
highlight LineNr ctermfg=grey

" For searching
set ignorecase
set incsearch
set hlsearch

" Display the cursorline and columnline
set cursorline
set cursorcolumn

" Set encoding to utf-8
set fileencoding=utf-8 encoding=utf-8

" Defines tab and shift width
set expandtab
set tabstop=4
set shiftwidth=4

" Show matching brackets
set showmatch

" Automatically remove trailing whitespace
autocmd! BufWrite * mark ' | silent! %s/\s\+$// | norm ''

" Always show the statusline
set laststatus=2

" Format the statusline - GitBranchInfoString() requires github.com/taq/vim-git-branch-info to work
set statusline=
set statusline+=\[%F]
set statusline+=\%r%m
set statusline+=\[%{GitBranchInfoTokens()[0]}]
set statusline+=\%=
set statusline+=\[%3p%%]
set statusline+=\[%3l:%3c]

" Do not create those annoying backup files
set nobackup
set nowritebackup

" Enhanced mode for command-line completion
set wildmenu

" Enable listing possible completions when completing file names
set wildmode=longest:full

" Skip certain endings while completing
set wildignore=*.o,*.a,*.la,*.lo,*.swp,.svn,.git,*.pyc,*.pyo
