# Sets the editor and other stuff
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

# Expand path to /usr/sbin and /sbin
export PATH=~/.bin:$PATH:/usr/sbin:/sbin

# Export language
unset LC_ALL
export LANG=en_US.UTF-8
export LC_MESSAGES=C

# Set the short date to YYYY-MM-DD
export LC_TIME=en_DK.UTF-8
