#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# mouse
hc mouseunbind --all

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4

hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close

hc keybind $Mod-Return spawn ${TERMINAL:-urxvtc}
hc keybind $Mod-d spawn shellex

# screen lock
hc keybind XF86Launch1 spawn i3lock -e -f -c 000000

# controling brightness
hc keybind XF86MonBrightnessUp   spawn xbacklight -inc 2
hc keybind XF86MonBrightnessDown spawn xbacklight -dec 2

# controlling the audio
hc keybind XF86AudioRaiseVolume spawn amixer set Master 2%+ unmute
hc keybind XF86AudioLowerVolume spawn amixer set Master 2%- unmute
hc keybind XF86AudioMute        spawn amixer set Master mute

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u split bottom 0.5
hc keybind $Mod-o split right  0.5

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-Left  resize left +$resizestep
hc keybind $Mod-Control-Down  resize down +$resizestep
hc keybind $Mod-Control-Up    resize up +$resizestep
hc keybind $Mod-Control-Right resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]}
do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ]
    then
        hc keybind "$Mod-$key"       use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r            remove
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# focus
hc keybind $Mod-BackSpace cycle_monitor
hc keybind $Mod-Tab       cycle_all +1
hc keybind $Mod-Shift-Tab cycle_all -1
hc keybind $Mod-c         cycle

# theme
hc set frame_gap  2
hc set window_gap 0

hc set frame_border_width  0
hc set window_border_width 1

hc set frame_bg_active_color      '#222222'
hc set window_border_active_color '#ff0000'
hc set window_border_normal_color '#5f676a'
hc set window_border_urgent_color '#cc3333'

# rules
hc unrule -F

# focus new clients
hc rule focus=on

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

